name: repository_dispatch

on: [repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering repository_dispatch"
      - name: Checkout
        uses: actions/checkout@v2
