name: workflow_dispatch
#on: [repository_dispatch]
on: [workflow_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow Dispatch"
      - name: Checkout
        uses: actions/checkout@v2
